config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :stockholders
  resources :requisitions
  resources :bids
  get   'bid/:id/pdf',              to: 'bids#pdf',                 as: 'bid_pdf'
  resources :qanswers
  resources :ianswers
  resources :messages
  resources :folders
  resources :notifications
  resources :questions
  resources :items
  resources :requests
  post  'assign/request',             to: 'requests#assign_request',  as: 'assign_request'
  post  'request/preview',            to: 'requests#preview_request', as: 'preview_request'      
  get   'request/:id/bids',           to: 'requests#compare_bids',    as: 'compare_bids'
  post  'request/set/winner',         to: 'requests#set_winner',      as: 'set_winner'
  get   'request/:id/export',         to: 'requests#export_excel',    as: 'export_excel'
  get   'request/:id/report',         to: 'requests#pdf',             as: 'open_report'
  get   'request/:id/download',       to: 'requests#download',        as: 'download'
  post  'request/delete/document',    to: 'requests#delete_document', as: 'delete_document'
  get   'request/:id/status/:status', to: 'requests#change_status',   as: 'change_status'
  post  'request/preview/invitation', to: 'requests#preview_invite',  as: 'preview_invitation'
  post  'request/:id/invite',         to: 'requests#invite_supplier', as: 'invite_supplier'
  
  resources :suppliers
  get   'request/:id/view/:token',    to: 'suppliers#view_request',   as: 'view_request'
  
  resources :companies
  post 'company/invite',                to: 'companies#invite_colleague',       as: 'invite_colleague'
  get  'accept/:user/invite/:company',  to: 'companies#accept_colleage_invite', as: 'accept_invite'
  post 'assign/requisition',            to: 'companies#assign_colleague',       as: 'assign_colleague'

  get 'dashboard/request', to: 'dashboard#trequest', as: 'dashboard_request'

  get 'dashboard/requisition'

  get 'dashboard/supplier'

  get 'dashboard/activity'

  get 'dashboard/message'

  get 'dashboard/report'

  devise_for :users

  # get '/home',            to: 'static#home',            as: 'home'  
  get '/privacy-policy',  to: 'static#privacy_policy',  as: 'privacy_policy'
  get '/terms-of-use',    to: 'static#terms_of_use',    as: 'terms_of_use'
  get '/contact',         to: 'static#contact',         as: 'contact'
  get '/demo',            to: 'static#demo',            as: 'demo'
  get '/prequalification',to: 'static#prequalification',as: 'prequalification'
  get '/requisition/bid', to: 'static#requisition',     as: 'requisition_bid'
  get '/vendor',          to: 'static#vendor',          as: 'vendor'
  get '/diligence',       to: 'static#diligence',       as: 'diligence'
  get '/about',		      to: 'static#company',         as: 'about'


  root 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :supplier
  belongs_to :request
  belongs_to :requisition
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    if params[:id].nil?
      if current_user.requests.exists?
        @request = current_user.requests.first
      elsif !current_user.supplier.nil?
        @request = current_user.supplier.requests.first
      end
    else
      @request = Request.find params[:id]
    end

    unless @request.nil?
      @messages   = @request.messages
      @requests   = current_user.requests
      unless current_user.supplier.nil?
        @supplier_requests = current_user.supplier.requests
        @requests = @requests.to_a.concat @supplier_requests.to_a
      end  
    end

    unless @requests.nil?
      @requests.uniq!
    else
      @requests = []
      redirect_to root_path
    end 
    
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully sent.' }
        format.json { render json: {  status: 'success', message: 'Message was successfully sent.' } }
      else
        format.html { render :new }
        format.json { render json: {  status: 'error', message: @message.errors.full_messages.join(',') } }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render json: {  status: 'success', message: 'Message was successfully updated.' } }
      else
        format.html { render :edit }
        format.json { render json: {  status: 'error', message: @message.errors.full_messages.join(',') } }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :attach, :from, :read, :user_id, :supplier_id, :request_id, :requisition_id )
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :attach %>
    <%= f.text_field :attach %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :supplier_id %>
    <%= f.text_field :supplier_id %>
  </div>

  <div class="field">
    <%= f.label :request_id %>
    <%= f.text_field :request_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<% provide(:title, "Messages") %>
<section style="min-height: 60vh;">
  <div class="container">
    <% if @requests.empty? %>
      <br><br>
      <h1 class="text-info text-center">Create, Send, Reply, Mark as read messages on Tenderbooks</h1>
      <hr>
      <div class="row">
        <div class="col-md-3 col-md-offset-3">
          <%= image_tag 'buyer/srm.png', class: 'img-responsive', style: 'margin: 0 auto;' %>  
        </div>
        <div class="col-md-4 text-center">
          <p>Buyer can send message and mark all messages for request between buyer and supplier on Tenderbooks.</p>
          <br>
          <%= link_to 'Schedule a live demo', 'javascript:;', class: 'btn btn-info btn-lg', 'data-confirm': 'Sorry, Live demo is not yet ready.' %><br><br>
          In order to see messages, Create <%= link_to 'RFQ', new_request_path('RFQ') %> / <%= link_to 'RFI', new_request_path('RFI') %> first.
        </div>        
      </div>
      <br><br>
    <% else %>

    <div class="row">
    	<div class="col-xs-12">
    		<div class="pull-right">
	    		<%= link_to 'Back to Request', @request, class: "btn btn-default btn-sm" %>
	    	</div>
    	</div>    	
    </div>

    <div class="row">
      <div class="col-md-4">
        <% unless @requests.nil? %>
          <% @requests.each do |request| %>
            <%= link_to( messages_path( id:request.id ) ) do %>         
              <div class="well <%= 'active' if request.id.to_i == @request.id.to_i %>">
                <h5>
                  <small class="pull-right">                
                    <span class="badge bg-blue">
                      <small class="text-white"><%= request.messages.count %> <i class="glyphicon glyphicon-triangle-right"></i></small>
                    </span>
                  </small>
                  #<%= request.id %> <%= request.name %><br><small><%= request.created_at.strftime("%b %d, %Y %H:%M") %></small>          
                </h5>
              </div>
             <% end %>
           <% end %>
        <% end %>        
      </div>
      <div class="col-md-8">
        <% unless @request.nil? %>
        <div class="well">
          <div>
            <button class="btn btn-default btn-sm" id="new-message">NEW MESSAGE</button>
            <button class="btn btn-default btn-sm pull-right" id="open-request-detail">OPEN REQUEST DETAILS</button>
          </div>

          <div id="message-request-detail">
            <hr>
            <pre>
              <%= @request.description %>
            </pre>
          </div> 

          <div id="new-message-div">
            <hr>
            <div class="alert" id="message-result"></div>
            <div class="form-group"><textarea class="form-control" rows="3" id="message-content" ></textarea></div>
            <hr>          
            <div class="text-right">
              <a 
                href="javascript:;" 
                class="btn btn-info text-uppercase" 
                id="send-message" 
                data-request='<%= @request.id %>'
                data-url='<%= messages_path %>'
                <% if current_user == @request.user %>
                data-buyer='<%= current_user.id %>'
                <% else %>
                data-supplier='<%= current_user.supplier.id %>'
                <% end %>
                >send message</a>
            </div>
          </div>         
          <hr>
          <% @messages.reverse_each do |message| %>
            <div>
              <small class="text-muted pull-right">
                <i class="glyphicon glyphicon-time"></i> <%= distance_of_time_in_words(Time.now, message.created_at) %> ago
              </small>
              <% if message.from == 'buyer' %>
              <h5><%= message.user.name %> : <em><%= @request.company.name %></em></h5>
                <% unless message.supplier.nil? %>
                  <b>To:</b>
                  <% unless message.supplier.name.nil? %>
                    <span class="text-muted"><%= message.supplier.name %>, <b><%= message.supplier.company %></b></span>
                  <% else %>
                    <span class="text-muted"><%= message.supplier.email %></span>
                  <% end %>
                <% end %>
              <% else %>
                <h5>
                  <% unless message.supplier.name.nil? %>
                    <%= message.supplier.name %> : <em><%= message.supplier.company %></em>
                  <% else %>
                    <%= message.supplier.email %>
                  <% end %>
                </h5>
              <% end %>              
              <div>                
                <% unless message.read %>
                  <% if ( message.from == 'buyer' and current_user != @request.user ) or 
                        ( message.from == 'supplier' and current_user == @request.user ) %>
                    <button class="btn btn-success btn-xs reply-message">
                      Reply
                    </button>
                    <button class="btn btn-info btn-xs mark-read" data-url="<%= message_url(message.id) %>" >
                      Mark as read
                    </button>
                  <% else %>
                    <small><span class="label label-warning">Unread</span></small>
                  <% end %>
                <% else %>
                <small><span class="label label-success">Read</span></small>
                <% end %>
              </div>
              <pre><%= message.content.html_safe %></pre>              
              <% unless message.attach.nil? %>
                <%= link_to 'Attach', '#'  %>
              <% end %>              
            </div>
            <hr>
          <% end %>
        </div>
        <% else %>
        <p>No messsage yet...</p>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Attach:</strong>
  <%= @message.attach %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @message.supplier %>
</p>

<p>
  <strong>Request:</strong>
  <%= @message.request %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>