config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :stockholders
  resources :requisitions
  resources :bids
  get   'bid/:id/pdf',              to: 'bids#pdf',                 as: 'bid_pdf'
  resources :qanswers
  resources :ianswers
  resources :messages
  resources :folders
  resources :notifications
  resources :questions
  resources :items
  resources :requests
  post  'assign/request',             to: 'requests#assign_request',  as: 'assign_request'
  post  'request/preview',            to: 'requests#preview_request', as: 'preview_request'      
  get   'request/:id/bids',           to: 'requests#compare_bids',    as: 'compare_bids'
  post  'request/set/winner',         to: 'requests#set_winner',      as: 'set_winner'
  get   'request/:id/export',         to: 'requests#export_excel',    as: 'export_excel'
  get   'request/:id/report',         to: 'requests#pdf',             as: 'open_report'
  get   'request/:id/download',       to: 'requests#download',        as: 'download'
  post  'request/delete/document',    to: 'requests#delete_document', as: 'delete_document'
  get   'request/:id/status/:status', to: 'requests#change_status',   as: 'change_status'
  post  'request/preview/invitation', to: 'requests#preview_invite',  as: 'preview_invitation'
  post  'request/:id/invite',         to: 'requests#invite_supplier', as: 'invite_supplier'
  
  resources :suppliers
  get   'request/:id/view/:token',    to: 'suppliers#view_request',   as: 'view_request'
  
  resources :companies
  post 'company/invite',                to: 'companies#invite_colleague',       as: 'invite_colleague'
  get  'accept/:user/invite/:company',  to: 'companies#accept_colleage_invite', as: 'accept_invite'
  post 'assign/requisition',            to: 'companies#assign_colleague',       as: 'assign_colleague'

  get 'dashboard/request', to: 'dashboard#trequest', as: 'dashboard_request'

  get 'dashboard/requisition'

  get 'dashboard/supplier'

  get 'dashboard/activity'

  get 'dashboard/message'

  get 'dashboard/report'

  devise_for :users

  # get '/home',            to: 'static#home',            as: 'home'  
  get '/privacy-policy',  to: 'static#privacy_policy',  as: 'privacy_policy'
  get '/terms-of-use',    to: 'static#terms_of_use',    as: 'terms_of_use'
  get '/contact',         to: 'static#contact',         as: 'contact'
  get '/demo',            to: 'static#demo',            as: 'demo'
  get '/prequalification',to: 'static#prequalification',as: 'prequalification'
  get '/requisition/bid', to: 'static#requisition',     as: 'requisition_bid'
  get '/vendor',          to: 'static#vendor',          as: 'vendor'
  get '/diligence',       to: 'static#diligence',       as: 'diligence'
  get '/about',		      to: 'static#company',         as: 'about'


  root 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to edit_user_registration_path, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to edit_user_registration_path, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:messages, :join_company, :reject_compay, :participate_request, :new_bid, :not_participate_request, :invit_request, :changed_request, :reminder_end, :request_decision, :label_tender_scoring, :submitted_requisition, :messages_requisition, :user_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<div class="panel panel-info">
  <div class="panel-heading"><h4 class="panel-title">NOTIFICATIONS</h4></div>
  <div class="panel-body">
    <%= form_for(notification) do |f| %>
    <% if notification.errors.any? %>
      <%= error_message notification %>
    <% end %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <b>Check which notifications you would like to get from TenderBooks.</b>
    <hr>
    <label>Messages</label>
    <div class="checkbox">
      <label>
        <%= f.check_box :messages %>Messages with other users and companies in TenderBooks
      </label>
    </div>
    <hr>
    <label>Notifications regarding your company</label>
    <div class="checkbox">
      <label>
        <%= f.check_box :join_company %>A user wants to join company
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :reject_compay %>You are removed from a company
      </label>
    </div>
    <hr>
    <label>Request notifications</label>
    <div class="checkbox">
      <label>
        <%= f.check_box :participate_request %>Supplier sends a request to participate on request
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :new_bid %>Supplier has mad a new bid
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :not_participate_request %>Supplier doesn't want to participate on request
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :invit_request %>Buyer invites you to participate on request
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :changed_request %>Buyer has changed the request
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :reminder_end %>Rminder that request is about to end
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :request_decision %>Notification about request decision
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :label_tender_scoring %>label_tender scoring
      </label>
    </div>
    <hr>
    <label>Requisitions</label>
    <div class="checkbox">
      <label>
        <%= f.check_box :submitted_requisition %>I wan to be notified when new requisition is submitted
      </label>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :messages_requisition %>Messages for requisitions that I'm managing
      </label>
    </div>
    <hr>
    <div class="text-right">
      <%= f.submit 'Save', class: 'btn btn-info' %>
    </div>
    <% end %>
  </div>
</div>

app/views/notifications/edit.html.erb
<% provide(:title, "Notification") %>
<section style="min-height: 60vh;">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= render 'form', notification: @notification %>
			</div>
			<div class="col-md-4">
				<%= render 'shared/sidebar', notification: true %>
			</div>
		</div>
	</div>
</section>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Messages</th>
      <th>Join company</th>
      <th>Reject compay</th>
      <th>Participate request</th>
      <th>New bid</th>
      <th>Not participate request</th>
      <th>Invit request</th>
      <th>Changed request</th>
      <th>Reminder end</th>
      <th>Request decision</th>
      <th>Label tender scoring</th>
      <th>Submitted requisition</th>
      <th>Messages requisition</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.messages %></td>
        <td><%= notification.join_company %></td>
        <td><%= notification.reject_compay %></td>
        <td><%= notification.participate_request %></td>
        <td><%= notification.new_bid %></td>
        <td><%= notification.not_participate_request %></td>
        <td><%= notification.invit_request %></td>
        <td><%= notification.changed_request %></td>
        <td><%= notification.reminder_end %></td>
        <td><%= notification.request_decision %></td>
        <td><%= notification.label_tender_scoring %></td>
        <td><%= notification.submitted_requisition %></td>
        <td><%= notification.messages_requisition %></td>
        <td><%= notification.user %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<% provide(:title, "Notification") %>
<section style="min-height: 60vh;">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= render 'form', notification: @notification %>
			</div>
			<div class="col-md-4">
				<%= render 'shared/sidebar', notification: true %>
			</div>
		</div>
	</div>
</section>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Messages:</strong>
  <%= @notification.messages %>
</p>

<p>
  <strong>Join company:</strong>
  <%= @notification.join_company %>
</p>

<p>
  <strong>Reject compay:</strong>
  <%= @notification.reject_compay %>
</p>

<p>
  <strong>Participate request:</strong>
  <%= @notification.participate_request %>
</p>

<p>
  <strong>New bid:</strong>
  <%= @notification.new_bid %>
</p>

<p>
  <strong>Not participate request:</strong>
  <%= @notification.not_participate_request %>
</p>

<p>
  <strong>Invit request:</strong>
  <%= @notification.invit_request %>
</p>

<p>
  <strong>Changed request:</strong>
  <%= @notification.changed_request %>
</p>

<p>
  <strong>Reminder end:</strong>
  <%= @notification.reminder_end %>
</p>

<p>
  <strong>Request decision:</strong>
  <%= @notification.request_decision %>
</p>

<p>
  <strong>Label tender scoring:</strong>
  <%= @notification.label_tender_scoring %>
</p>

<p>
  <strong>Submitted requisition:</strong>
  <%= @notification.submitted_requisition %>
</p>

<p>
  <strong>Messages requisition:</strong>
  <%= @notification.messages_requisition %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>