config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :stockholders
  resources :requisitions
  resources :bids
  get   'bid/:id/pdf',              to: 'bids#pdf',                 as: 'bid_pdf'
  resources :qanswers
  resources :ianswers
  resources :messages
  resources :folders
  resources :notifications
  resources :questions
  resources :items
  resources :requests
  post  'assign/request',             to: 'requests#assign_request',  as: 'assign_request'
  post  'request/preview',            to: 'requests#preview_request', as: 'preview_request'      
  get   'request/:id/bids',           to: 'requests#compare_bids',    as: 'compare_bids'
  post  'request/set/winner',         to: 'requests#set_winner',      as: 'set_winner'
  get   'request/:id/export',         to: 'requests#export_excel',    as: 'export_excel'
  get   'request/:id/report',         to: 'requests#pdf',             as: 'open_report'
  get   'request/:id/download',       to: 'requests#download',        as: 'download'
  post  'request/delete/document',    to: 'requests#delete_document', as: 'delete_document'
  get   'request/:id/status/:status', to: 'requests#change_status',   as: 'change_status'
  post  'request/preview/invitation', to: 'requests#preview_invite',  as: 'preview_invitation'
  post  'request/:id/invite',         to: 'requests#invite_supplier', as: 'invite_supplier'
  
  resources :suppliers
  get   'request/:id/view/:token',    to: 'suppliers#view_request',   as: 'view_request'
  
  resources :companies
  post 'company/invite',                to: 'companies#invite_colleague',       as: 'invite_colleague'
  get  'accept/:user/invite/:company',  to: 'companies#accept_colleage_invite', as: 'accept_invite'
  post 'assign/requisition',            to: 'companies#assign_colleague',       as: 'assign_colleague'

  get 'dashboard/request', to: 'dashboard#trequest', as: 'dashboard_request'

  get 'dashboard/requisition'

  get 'dashboard/supplier'

  get 'dashboard/activity'

  get 'dashboard/message'

  get 'dashboard/report'

  devise_for :users

  # get '/home',            to: 'static#home',            as: 'home'  
  get '/privacy-policy',  to: 'static#privacy_policy',  as: 'privacy_policy'
  get '/terms-of-use',    to: 'static#terms_of_use',    as: 'terms_of_use'
  get '/contact',         to: 'static#contact',         as: 'contact'
  get '/demo',            to: 'static#demo',            as: 'demo'
  get '/prequalification',to: 'static#prequalification',as: 'prequalification'
  get '/requisition/bid', to: 'static#requisition',     as: 'requisition_bid'
  get '/vendor',          to: 'static#vendor',          as: 'vendor'
  get '/diligence',       to: 'static#diligence',       as: 'diligence'
  get '/about',		      to: 'static#company',         as: 'about'


  root 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="<% unless user_signed_in? %>skew<% end %>">
    <div class="container text-center" >
      <%= image_tag 'favicon.png', class: 'footer-logo' %>
      <!-- <p class="text-blue">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> -->
      <div class="footer-navigation">
        <a href="#">About Us</a> | 
        <a href="#">Contact Us</a> | 
        <%= link_to 'Privacy and policy', privacy_policy_path %> |
        <%= link_to 'Terms of use', terms_of_use_path %>
      </div>
      <div class="social-icons">
        <ul>
          <li><a class="envelope" href="#"><i class="fa fa-envelope"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li> 
          <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a class="tumblr" href="#"><i class="fa fa-tumblr-square"></i></a></li>
        </ul>
      </div>
      <div class="text-muted copyright">Copyright&copy;TendorBooks powered by Mtenders, All right reserved.</div>     
    </div>
  </footer>

app/views/shared/_header.html.erb
<% if user_signed_in? %>

<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
        <%= link_to "#{image_tag('logo.png')} <small>Powered by Mtenders</small>".html_safe, root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to '<i class="glyphicon glyphicon-tasks"></i> Requests'.html_safe, requests_path %>
          </li>
          <li>
            <%= link_to '<i class="glyphicon glyphicon-list"></i> Requisitions'.html_safe, requisitions_path %>
          </li>
          <% unless current_user.supplier.nil? %>
            <li>
              <%= link_to '<i class="glyphicon glyphicon-edit"></i> Bids'.html_safe, bids_path %>
            </li>
          <% end %>
          <li>
            <%= link_to '<i class="glyphicon glyphicon-user"></i> Suppliers'.html_safe, suppliers_path %>
          </li>
          <!--<li>
            <%= link_to '<i class="glyphicon glyphicon-star"></i> Activities'.html_safe, dashboard_activity_path %>
          </li> -->
          <li>
            <%= link_to '<i class="glyphicon glyphicon-envelope"></i> Messages'.html_safe, messages_path %>
          </li>
          <li>
            <%= link_to '<i class="glyphicon glyphicon-stats"></i> Reports'.html_safe, dashboard_report_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown" >
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
              <span class="glyphicon glyphicon-user"></span> 
              <% if current_company.nil? %>
                <%= current_user.name %> <span class="caret">
              <% else %>
                <%= current_company.name %>
              <% end %>
              </span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu2">
              <% current_user.companies.each do |company| %>
                <li><%= link_to company.name, edit_company_path( company ) %></li>
              <% end %>
              <li role="presentation">
                <%= link_to 'Settings', edit_user_registration_path %>
              </li>
              <li role="presentation" class="divider"></li>
              <li role="presentation">
                <%= link_to '<span class="glyphicon glyphicon-log-out"></span> Log Out'.html_safe, destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<% else %>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
        <%= link_to "#{image_tag('logo.png')} <small>Powered by Mtenders</small>".html_safe, root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Solutions <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li role="presentation">
              	<%= link_to 'Vendor Prequalification', prequalification_path %>
              </li>
              <li role="presentation">
              	<%= link_to 'Requisition & Bids', requisition_bid_path %>
              </li>
              <li role="presentation">
              	<%= link_to 'Vendor Registration', vendor_path %>
              </li>              
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            	Supplier Due Diligence <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu2">
              <li role="presentation">
              	<%= link_to 'Due dilligence', diligence_path %>
              </li>
            </ul>
          </li>
          <!-- <li><a href="#">Pricing</a></li> -->
          <li>
            <%= link_to 'Company', about_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to '<span class="glyphicon glyphicon-user"></span> <span class="hidden-sm" >Sign Up</span>'.html_safe, new_user_registration_path %>              
          </li>
          <li>
            <%= link_to '<span class="glyphicon glyphicon-log-in"></span> <span class="hidden-sm" >Login</span>'.html_safe, new_user_session_path %>              
          </li>
        </ul>
      </div>
    </div>
  </nav>

<% end %>

app/views/shared/_messages.html.erb
<div <% unless user_signed_in? %> style="margin-top: 100px; margin-bottom: -100px;" <% end %> >
	<div class="container">
		<% flash.each do |key, value| %>
		  <div class="alert alert-<%= key %>">
		    <a href="javascript:;" data-dismiss="alert" class="close">×</a>
		    <ul>
		      <li>
		        <%= value %>
		      </li>
		    </ul>
		  </div>
		<% end %>		
	</div>
</div>

app/views/shared/_sidebar.html.erb
<div class="panel-group">
  <div class="panel panel-info">
    <div class="panel-heading dropdown">
      <a href="javascript:;" data-toggle="dropdown">
        <% if defined? new_company %>
          Add Company
        <% else %>
          <% if current_company.nil? %>
          Add Company
          <% else %>
          <%= current_company.name %>
          <% end %>
        <% end %> <i class="glyphicon glyphicon-triangle-bottom pull-right"></i></a>
        <ul class="dropdown-menu">
          <% current_user.companies.each do |company| %>
          <li><%= link_to company.name, edit_company_path( company ) %></li>
          <% end %>
          <li class="divider"></li>
          <li>
            <%= link_to 'Add Company', new_company_path, class: 'btn btn-info add-company' %>
          </li>
        </ul>
      </div>
      <div class="panel-body">
        <% if defined? new_company %>
          <%= image_tag 'buyer/noimageCompany.gif', class: 'img-responsive', style: 'margin: 0 auto;' %>
        <% else %>
          <% if current_company.nil? %>
            <%= image_tag 'buyer/noimageCompany.gif', class: 'img-responsive', style: 'margin: 0 auto;' %>
          <% elsif current_company.logo.empty? %>
            <%= image_tag 'buyer/noimageCompany.gif', class: 'img-responsive', style: 'margin: 0 auto;' %>
          <% else %>
            <%= image_tag current_company.logo, class: 'img-responsive', style: 'margin: 0 auto;' %>
          <% end %>
        <% end %>                        
      </div>
    </div>

    <% if defined? new_company %>
      <div class="panel panel-success">
        <div class="panel-heading"><i class="glyphicon glyphicon-triangle-left"></i> Add Company</div>
      </div>
    <% else %>
      <% unless current_company.nil? %>
        <% if defined? company %>
          <div class="panel panel-success">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> General'.html_safe, edit_company_path(current_company) %>
            </div>
          </div>
        <% else %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> General'.html_safe, edit_company_path(current_company) %>
            </div>
          </div>
        <% end %>

        <% if defined? company_user %>
          <div class="panel panel-success">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> Company users'.html_safe, company_path(current_company) %>
            </div>
          </div>
        <% else %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> Company users'.html_safe, company_path(current_company) %>
            </div>
          </div>
        <% end %>
        
        <% if defined? subscription %>
          <div class="panel panel-success">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> Subscription'.html_safe, '#' %>
            </div>
          </div>
        <% else %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> Subscription'.html_safe, '#' %>
            </div>
          </div>
        <% end %>

      <% end %>
    <% end %>

  </div>

  <hr>

  <div class="panel-group">
    <% if defined? user %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> Your profile'.html_safe, edit_user_registration_path %>
        </div>
      </div>
    <% else %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> Your profile'.html_safe, edit_user_registration_path %>
        </div>
      </div>
    <% end %>

    <% if defined? notification %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <% if current_user.notification.nil? %>
          <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> Notifications'.html_safe, new_notification_path %>
          <% else %>
          <%= link_to '<i class="glyphicon glyphicon-triangle-left"></i> Notifications'.html_safe, edit_notification_path(current_user.notification) %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <% if current_user.notification.nil? %>
          <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> Notifications'.html_safe, new_notification_path %>
          <% else %>
          <%= link_to '<i class="glyphicon glyphicon-triangle-right"></i> Notifications'.html_safe, edit_notification_path(current_user.notification) %>
          <% end %>      
        </div>
      </div>
    <% end %>
    
  </div>